UserProject_1/Models/CustomerStatus.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UserProject_1.Models
{
    public class CustomerStatus
    {
        [Key]
        [DisplayName("S_N.O")]
        public int Id { get; set; }
        public double Rent { get; set; }
        public double Ebill { get; set; }
        public DateTime Date { get; set; }
        public string Due { get; set; }
        public string Status { get; set; }

        public int CustomerDetailId { get; set; }
        public CustomerDetails customerDetails { get; set; }
    }
}

UserProject_1/Controllers/CustomerDetailController.cs
using Microsoft.AspNetCore.Mvc;
using UserProject_1.Connection;
using UserProject_1.Models;

namespace UserProject_1.Controllers
{
    public class CustomerDetailController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CustomerDetailController(ApplicationDbContext db, IWebHostEnvironment webHostEnvironment)
        {
            this._db = db;
            this._webHostEnvironment = webHostEnvironment;
        }

        [HttpGet]
        public IActionResult Index()
        {
            string username = HttpContext.Session.GetString("Username");
            string phone = HttpContext.Session.GetString("Phone");

            List<CustomerDetails> customerDetails;

            if (username == "Admin")
            {
                customerDetails = _db.CustDetail.ToList();
            }
            else
            {
                customerDetails = _db.CustDetail.Where(c => (c.Phone == phone) && c.Name == username).ToList();
            }
          
            return View(customerDetails);
        }

        [HttpGet]   
        public IActionResult AddCustomer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddCustomer(CustomerDetails details, IFormFile? ProfileImage, IFormFile? IdProof)
        {
            try
            {
                if (ProfileImage != null && IdProof != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(ProfileImage.FileName);
                    string uploadPath = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");

                    string IdProofFilePath = Guid.NewGuid().ToString() + Path.GetExtension(IdProof.FileName);
                    string IdProofUploadPath = Path.Combine(_webHostEnvironment.WebRootPath, "Idproof");

                    if (!Directory.Exists(uploadPath))
                    {
                        Directory.CreateDirectory(uploadPath);
                    }
                    if (!Directory.Exists(IdProofUploadPath))
                    {
                        Directory.CreateDirectory(IdProofUploadPath);
                    }

                    string filePath = Path.Combine(uploadPath, fileName);
                    string IdproofPath = Path.Combine(IdProofUploadPath, IdProofFilePath);

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        ProfileImage.CopyTo(fileStream);
                    }

                    using (var IdFileStream = new FileStream(IdproofPath, FileMode.Create))
                    {
                        IdProof.CopyTo(IdFileStream);
                    }

                    details.ProfileImageUrl = "/uploads/" + fileName;
                    details.IdProof = "/Idproof/" + IdProofFilePath;
                }
                else
                {
                    details.ProfileImageUrl = "/lib/images.png"; // Default image
                }

                _db.CustDetail.Add(details);
                _db.SaveChanges();
                TempData["success"] = "Customer Added successfully";
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                TempData["error"] = "An error occurred while uploading files: " + e.Message;
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public IActionResult EditCustomer(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            CustomerDetails detail = _db.CustDetail.First(x => x.CustomerDetailId == id);
            return View(detail);
        }

        [HttpPost]
        public IActionResult EditCustomer(CustomerDetails newDetail, IFormFile? ProfileImage)
        {
            CustomerDetails oldDetail = _db.CustDetail.FirstOrDefault(x => x.CustomerDetailId == newDetail.CustomerDetailId);

            if (oldDetail != null)
            {
                if (ProfileImage != null)
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(ProfileImage.FileName);
                    string uploadPath = Path.Combine(_webHostEnvironment.WebRootPath, "uploads");

                    if (!Directory.Exists(uploadPath))
                    {
                        Directory.CreateDirectory(uploadPath);
                    }

                    string filePath = Path.Combine(uploadPath, fileName);
                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        ProfileImage.CopyTo(fileStream);
                    }

                    oldDetail.ProfileImageUrl = "/uploads/" + fileName;
                }

                oldDetail.Name = newDetail.Name;
                oldDetail.Email = newDetail.Email;
                oldDetail.Phone = newDetail.Phone;
                oldDetail.Address = newDetail.Address;
                oldDetail.Deposit = newDetail.Deposit;
                oldDetail.JoiningDate = newDetail.JoiningDate;
                _db.SaveChanges();
                TempData["success"] = "Customer Updated successfully";
                return RedirectToAction("Index");
            }

            TempData["error"] = "Customer Not Updated !!!";
            return View(newDetail);
        }

        [HttpGet]
        public IActionResult DeleteCustomer(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            CustomerDetails detail = _db.CustDetail.First(x => x.CustomerDetailId == id);
            return View(detail);
        }

        [HttpPost, ActionName("DeleteCustomer")]
        public IActionResult Delete(int? id)
        {
            if (id != null && id != 0)
            {
                CustomerDetails? detail = _db.CustDetail.Find(id);
                if (detail == null)
                {
                    return NotFound(detail);
                }

                // Delete Image from Server
                if (!string.IsNullOrEmpty(detail.ProfileImageUrl) && detail.ProfileImageUrl != "/lib/default-profile.png")
                {
                    string filePath = Path.Combine(_webHostEnvironment.WebRootPath, detail.ProfileImageUrl.TrimStart('/'));
                    if (System.IO.File.Exists(filePath))
                    {
                        System.IO.File.Delete(filePath);
                    }
                }

                _db.CustDetail.Remove(detail);
                _db.SaveChanges();
                TempData["warning"] = "Customer Deleted successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Customer Not Deleted !!!";
            return RedirectToAction("Home");
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            var customer = _db.CustDetail.FirstOrDefault(c => c.CustomerDetailId == id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }
    }
}

UserProject_1/Controllers/CustomerStatusController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserProject_1.Connection;
using UserProject_1.Models;

namespace UserProject_1.Controllers
{
    public class CustomerStatusController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CustomerStatusController(ApplicationDbContext db)
        {
            this._db = db;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            List<CustomerStatus> customerStatuses = _db.CustStatus
            .Where(x => x.CustomerDetailId == id)
            .ToList();
            ViewData["CustomerId"] = id;
            return View(customerStatuses);
        }

        [HttpGet]
        public IActionResult AddStatus(int customerID)
        {
            if (customerID == 0)
            {
                return NotFound("Customer ID is required.");
            }

            var status = new CustomerStatus
            {
                CustomerDetailId = customerID
            };

            return View(status);
        }

        [HttpPost]
        public IActionResult AddStatus(CustomerStatus details)
        {
            if (details.CustomerDetailId == 0)
            {
                TempData["error"] = "Invalid Customer ID.";
                return View(details);
            }

            // Manually load CustomerDetails from DB
            details.customerDetails = _db.CustDetail
                .FirstOrDefault(c => c.CustomerDetailId == details.CustomerDetailId);

            var customer = _db.CustDetail
            .Include(c => c.CustomerStatuses) // <-- This will load the related statuses
            .FirstOrDefault(c => c.CustomerDetailId == details.CustomerDetailId);

            _db.CustStatus.Add(details);
            _db.SaveChanges();
            TempData["success"] = "Data Added successfully";
            return RedirectToAction("Index");

            return View(details);
        }

        [HttpGet]
        public IActionResult EditStatus(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            CustomerStatus status = _db.CustStatus.First(x => x.Id == id);
            return View(status);
        }
        [HttpPost]
        public IActionResult EditCustomer(CustomerStatus newStatus)
        {
            if (newStatus == null)
            {
                TempData["error"] = "Invalid data submitted!";
                return View(newStatus);
            }

            CustomerStatus oldStatus = _db.CustStatus.FirstOrDefault(x => x.Id == newStatus.Id);

            // Update the properties
            oldStatus.Rent = newStatus.Rent;
            oldStatus.Ebill = newStatus.Ebill;
            oldStatus.Date = newStatus.Date;
            oldStatus.Due = newStatus.Due;
            oldStatus.Status = newStatus.Status;
            _db.SaveChanges();
            TempData["success"] = "Status Updated successfully";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DeleteStatus(int? id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            CustomerStatus detail = _db.CustStatus.First(x => x.Id == id);
            return View(detail);
        }

        [HttpPost, ActionName("DeleteStatus")]
        public IActionResult Delete(int? id)
        {
            if (id != null && id != 0)
            {
                CustomerStatus? status = _db.CustStatus.Find(id);
                if (status == null)
                {
                    return NotFound(status);
                }
                _db.CustStatus.Remove(status);
                _db.SaveChanges();
                TempData["warning"] = "Recors Deleted successfully";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Record Not Deleted !!!";
            return RedirectToAction("Home");
        }
    }
}

UserProject_1/Views/CustomerStatus/AddStatus.cshtml
@model CustomerStatus

<h1>Customer Status</h1>

<form asp-action="AddStatus" method="post">
    <input type="hidden" asp-for="CustomerDetailId" />

    <div class="form-group">
        <label asp-for="Rent">Rent</label>
        <input asp-for="Rent" class="form-control" placeholder="Enter Rent Amount">
    </div>

    <div class="form-group">
        <label asp-for="Ebill">Ebill</label>
        <input asp-for="Ebill" class="form-control" placeholder="Enter Ebill Amount">
    </div>

    <div class="form-group">
        <label asp-for="Date">Date</label>
        <input asp-for="Date" type="date" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Due">Due</label>
        <input asp-for="Due" type="text" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Status">Status</label>
        <input asp-for="Status" class="form-control" placeholder="Enter Status">
    </div>

    <div class="d-flex gap-2">
        <button type="submit" class="btn btn-primary"><i class="bi bi-person-plus-fill"></i> Add</button>
        <a asp-controller="CustomerStatus" asp-action="Index" class="btn btn-dark"><i class="bi bi-backspace"></i> Back</a>
    </div>
</form>
            

UserProject_1/Views/CustomerStatus/DeleteStatus.cshtml
@model CustomerStatus
<h1>Are yo Sure you want to delete status record !!!</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="Rent">Rent</label>
        <input asp-for="Rent" class="form-control" disabled />
    </div>
    <div class="form-group">
        <label asp-for="Date">Date</label>
        <input asp-for="Date" class="form-control" disabled>
    </div>
    <div class="form-group">
        <label asp-for="Ebill">Ebill</label>
        <input asp-for="Ebill" class="form-control" disabled>
    </div>
    <div class="form-group">
        <label asp-for="Due">Due</label>
        <input asp-for="Due" class="form-control" disabled>
    </div>
    <div class="form-group">
        <label asp-for="Status">Status</label>
        <input asp-for="Status" class="form-control" disabled>
    </div>
    <div class="d-flex gap-2">
        <div style="margin-top:4px"><button type="submit" class="btn btn-danger"><i class="bi bi-trash"></i> Delete</button></div>
        <div style="margin-top:4px"><a asp-controller="CustomerStatus" asp-action="Index" class="btn btn-dark"><i class="bi bi-backspace"></i> Back</a></div>
    </div>
</form>

UserProject_1/Views/CustomerStatus/EditStatus.cshtml
@model CustomerStatus

<form asp-action="EditCustomer" method="post">
    <div class="form-group">
        <label asp-for="Rent">Rent</label>
        <input asp-for="Rent" class="form-control" id="customername" placeholder="Enter Rent Amount">
    </div>
    <div class="form-group">
        <input type="hidden" asp-for="Id" />
    </div>
    <div class="form-group">
        <label asp-for="Ebill">Ebill</label>
        <input asp-for="Ebill" class="form-control" id="customername" placeholder="Enter Electricity Bill">
    </div>
    <div class="form-group">
        <label asp-for="Date">Date</label>
        <input asp-for="Date" class="form-control" type="date" id="customeraddress" placeholder="Enter Date">
    </div>
    <div class="form-group">
        <label asp-for="Due">Due</label>
        <input asp-for="Due" class="form-control" id="depositeamount" placeholder="Enter Due Amount">
    </div>
    <div class="form-group">
        <label asp-for="Status">Status</label>
        <input asp-for="Status" class="form-control" id="joiningdate" placeholder="Enter Status">
    </div>
    <div class="d-flex gap-2">
        <div style="margin-top:4px"><button type="submit" class="btn btn-primary"><i class="bi bi-pencil-square"></i> Update</button></div>
        <div style="margin-top:4px"><a asp-controller="CustomerStatus" asp-action="Index" class="btn btn-dark"><i class="bi bi-backspace"></i> Back</a></div>
    </div>
</form>

UserProject_1/Views/CustomerStatus/Index.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model List<CustomerStatus>
@{
    var customerId = ViewData["CustomerId"];
}
<partial name="_Notification" />
<div>
    @if (Model == null || !Model.Any())
    {
        <h1>No data in record !!!</h1>
    }
    else
    {
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Rent</th>
                    <th>Ebill</th>
                    <th>Due</th>
                    <th>Status</th>
                    @if (HttpContextAccessor.HttpContext.Session.GetString("Username") == "Admin")
                    {
                        <th>Operations</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Date</td>
                        <td>@obj.Rent</td>
                        <td>@obj.Ebill</td>
                        <td>@obj.Due</td>
                        <td>@obj.Status</td>
                        @if (HttpContextAccessor.HttpContext.Session.GetString("Username") == "Admin")
                        {
                            <td>
                                <a asp-controller="CustomerStatus" asp-action="EditStatus" asp-route-Id="@obj.Id" class="btn btn-info"><i class="bi bi-pencil-square"></i>Edit</a>
                                <a asp-controller="CustomerStatus" asp-action="DeleteStatus" asp-route-Id="@obj.Id" class="btn btn-danger"><i class="bi bi-trash"></i>Delete</a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
</div>
<div>
    @if (HttpContextAccessor.HttpContext.Session.GetString("Username") == "Admin")
    {
        <a asp-controller="CustomerStatus" asp-route-customerID="@customerId" asp-action="AddStatus" class="btn btn-primary"><i class="bi bi-person-plus"></i> Add</a>
    }
    <a asp-controller="CustomerDetail" asp-action="Index" class="btn btn-dark"><i class="bi bi-backspace"></i> Back</a>
</div>